#name, start position, length, planned decoding method
DECODER_DEFAULT = 'pic_any'
DECODER_NUMERIC = 'pic_numeric'
DATE_DECODER = 'pic_yyyymmdd'

DASTATUSROOT01 = [
    ('RRC-TAPE-RECORD-ID', 0, 2, DECODER_DEFAULT),
    ('DA-PERMIT-NUMBER', 2, 7, DECODER_NUMERIC),
    ('DA-STATUS-SEQUENCE-NUMBER', 9, 2, DECODER_NUMERIC),
    ('DA-PERMIT-COUNTY-CODE', 11, 3, DECODER_NUMERIC),
    ('DA-LEASE-NAME', 14, 32, DECODER_DEFAULT),
    ('DA-DISTRICT', 46, 2, DECODER_DEFAULT),
    ('DA-PERMIT-WELL-NUMBER', 48, 6, DECODER_DEFAULT),
    ('DA-PERMIT-TOTAL-DEPTH', 54, 5, DECODER_NUMERIC),
    ('DA-PERMIT-OPERATOR-NUMBER', 59, 6, DECODER_NUMERIC),
    ('DA-TYPE-APPLICATION', 65, 2, DECODER_DEFAULT),
    ('DA-OTHER-EXPLANATION', 67, 30, DECODER_DEFAULT),
    ('DA-ADDRESS-UNIQUE-NUMBER', 97, 6, DECODER_NUMERIC),
    ('DA-ZIP-CODE', 103, 9, DECODER_NUMERIC),
    ('DA-FICHE-SET-NUMBER', 112, 6, DECODER_NUMERIC),
    ('DA-ONSHORE-COUNTY', 118, 3, DECODER_NUMERIC),
    ('DA-RECEIVED-DATE', 121, 8, DATE_DECODER),
    ('DA-PERMIT-ISSUED-DATE', 129, 8, DATE_DECODER),
    ('DA-PERMIT-AMENDED-DATE', 137, 8, DATE_DECODER),
    ('DA-PERMIT-EXTENDED-DATE', 145, 8, DATE_DECODER),
    ('DA-PERMIT-SPUD-DATE', 153, 8, DATE_DECODER),
    ('DA-PERMIT-SURFACE-CASING-DATE', 161, 8, DATE_DECODER),
    ('DA-WELL-STATUS', 169, 1, DECODER_DEFAULT),
    ('DA-PERMIT-WELL-STATUS-DATE', 170, 8, DATE_DECODER),
    ('DA-PERMIT-EXPIRED-DATE', 178, 8, DATE_DECODER),
    ('DA-PERMIT-CANCELLED-DATE', 186, 8, DATE_DECODER),
    ('DA-CANCELLATION-REASON', 194, 30, DECODER_DEFAULT),
    ('DA-P12-FILED-FLAG', 224, 1, DECODER_DEFAULT),
    ('DA-SUBSTANDARD-ACREAGE-FLAG', 225, 1, DECODER_DEFAULT),
    ('DA-RULE-36-FLAG ', 226, 1, DECODER_DEFAULT),
    ('DA-H9-FLAG', 227, 1, DECODER_DEFAULT),
    ('DA-RULE-37-CASE-NUMBER', 228, 7, DECODER_DEFAULT),
    ('DA-RULE-38-DOCKET-NUMBER', 235, 7, DECODER_NUMERIC),
    ('DA-LOCATION-FORMATION-FLAG', 242, 1, DECODER_DEFAULT),
    ('DA-OLD-SURFACE-LOCATION', 243, 82, DECODER_DEFAULT),
    ('DA-SURFACE-ACRES', 325, 6, DECODER_NUMERIC),
    ('DA-SURFACE-MILES-FROM-CITY', 333, 4, DECODER_NUMERIC),
    ('DA-SURFACE-DIRECTION-FROM-CITY', 339, 6, DECODER_DEFAULT),
    ('DA-SURFACE-NEAREST-CITY', 345, 13, DECODER_DEFAULT),
    ('DA-SURFACE-LEASE-FEET-1', 358, 6, DECODER_NUMERIC),
    ('DA-SURFACE-LEASE-DIRECTION-1', 366, 13, DECODER_DEFAULT),
    ('DA-SURFACE-LEASE-FEET-2', 379, 6, DECODER_NUMERIC),
    ('DA-SURFACE-LEASE-DIRECTION-2', 387, 13, DECODER_DEFAULT),
    ('DA-SURFACE-SURVEY-FEET-1', 400, 6, DECODER_NUMERIC),
    ('DA-SURFACE-SURVEY-DIRECTION-1', 408, 13, DECODER_DEFAULT),
    ('DA-SURFACE-SURVEY-FEET-2', 421, 6, DECODER_NUMERIC),
    ('DA-SURFACE-SURVEY-DIRECTION-2 ', 429, 13, DECODER_DEFAULT),
    ('DA-NEAREST-WELL', 442, 28, DECODER_DEFAULT),
    ('DA-NEAREST-WELL-FORMAT-FLAG', 470, 1, DECODER_DEFAULT),
    ('DA-FINAL-UPDATE', 471, 8, DATE_DECODER),
    ('DA-CANCELLED-FLAG', 479, 1, DECODER_DEFAULT),
    ('DA-SPUD-IN-FLAG', 480, 1, DECODER_DEFAULT),
    ('DA-DIRECTIONAL-WELL-FLAG', 481, 1, DECODER_DEFAULT),
    ('DA-SIDETRACK-WELL-FLAG', 482, 1, DECODER_DEFAULT),
    ('DA-MOVED-INDICATOR', 483, 1, DECODER_DEFAULT),
    ('DA-PERMIT-CONV-ISSUED-DATE', 484, 9, DECODER_NUMERIC),
    ('DA-RULE-37-GRANTED-CODE', 492, 1, DECODER_DEFAULT),
    ('DA-HORIZONTAL-WELL-FLAG', 493, 1, DECODER_DEFAULT),
    ('DA-DUPLICATE-PERMIT-FLAG', 494, 1, DECODER_DEFAULT),
    ('DA-NEAREST-LEASE-LINE', 495, 7, DECODER_DEFAULT),
    ('API-NUMBER', 502, 8, DECODER_NUMERIC)
]


def daLayout(startVal):
    layouts_map = {
        '01': {'name': 'UICROOT01', 'layout': DASTATUSROOT01},
    }
    returnval = layouts_map[startVal]

    return returnval